import Head from "next/head";
import { Open_Sans } from "next/font/google";
import {
  HvVerticalNavigation,
  HvVerticalNavigationTree,
  HvVerticalNavigationActions,
  HvVerticalNavigationAction,
} from "@hitachivantara/uikit-react-core";
import { User, LogOut } from "@hitachivantara/uikit-react-icons";

const openSans = Open_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${openSans.className}`}>
        <div
          style={{
            display: "flex",
            height: 530,
            width: 220,
          }}
        >
          <HvVerticalNavigation>
            <HvVerticalNavigationTree
              id="nav-tree"
              aria-label="Example 3 navigation"
              collapsible
              data={[
                {
                  id: "00",
                  label: "Instalation Overview",
                },
                {
                  data: [
                    {
                      id: "01-01",
                      label: "Ambient Monitoring",
                    },
                    {
                      id: "01-02",
                      label: "Server Status Summary",
                    },
                  ],
                  id: "01",
                  label: "Hardware",
                },
                {
                  data: [
                    {
                      id: "02-01",
                      label: "Buckets",
                    },
                    {
                      id: "02-02",
                      label: "Admin Users",
                    },
                    {
                      data: [
                        {
                          id: "02-03-01",
                          label: "Rest API",
                        },
                        {
                          id: "02-03-02",
                          label: "License",
                        },
                      ],
                      id: "02-03",
                      label: "Log Bundle",
                    },
                  ],
                  id: "02",
                  label: "System",
                },
              ]}
              defaultExpanded
              mode="treeview"
              onChange={function Ta() {}}
              selected="01-01"
            />
            <HvVerticalNavigationActions>
              <HvVerticalNavigationAction icon={<User />} label="Profile" />
              <HvVerticalNavigationAction icon={<LogOut />} label="Logout" />
            </HvVerticalNavigationActions>
          </HvVerticalNavigation>
        </div>
      </main>
    </>
  );
}
